/**
 * Copyright (c) 2021 Eclipse contributors and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.justj.codegen.model.util;


import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.URIConverter;


public class TemurinIndexer
{
  private static final Pattern ASSETS_PATTERN = Pattern.compile("\"link\": \"([^\"]+\\.(zip|tar.gz))\"");

  private static final Pattern VERSION_PATTERN = Pattern.compile("jdk-([0-9.+]+)/");

  private static final Pattern BETA_VERSION_PATTERN = Pattern.compile("jdk-([0-9.+]+)-ea-beta/");

  private static final String BEGIN_MARKER = "// Begin generated by /org.eclipse.justj.codegen/src/org/eclipse/justj/codegen/model/util/TemurinIndexer.java";

  private static final String END_MARKER = "// End generated by /org.eclipse.justj.codegen/src/org/eclipse/justj/codegen/model/util/TemurinIndexer.java";

  private static final String BEGIN_BETA_MARKER = "// Begin beta generated by /org.eclipse.justj.codegen/src/org/eclipse/justj/codegen/model/util/TemurinIndexer.java";

  private static final String END_BETA_MARKER = "// End beta generated by /org.eclipse.justj.codegen/src/org/eclipse/justj/codegen/model/util/TemurinIndexer.java";

  private static Path cache;

  public static void main(String[] argsx) throws Exception
  {
    List<String> arguments = new ArrayList<String>(List.of(argsx));
    if (arguments.size() > 1)
    {
      cache = Path.of(arguments.remove(0));
    }

    generate(false, arguments);
    generate(true, arguments);
  }

  public static void generate(boolean beta, List<String> arguments) throws Exception
  {
    PrintStream out = System.out;

    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()
      {
        int start = 0;

        @Override
        public void flush() throws java.io.IOException
        {
          super.flush();
          System.out.write(buf, start, count - start);
          start = count;
        }
      };

    out = new PrintStream(byteArrayOutputStream, true, StandardCharsets.UTF_8);

    out.println(beta ? BEGIN_BETA_MARKER : BEGIN_MARKER);

    for (String repo : beta ? new String []{ "27" } : new String []{ "11", "17", "21", "25", "26" })
    {
      URI releasesURI = beta
        ? URI.createURI("https://api.adoptium.net/v3/assets/feature_releases/" + repo + "/ea?image_type=jdk&jvm_impl=hotspot&project=jdk&vendor=eclipse")
        : URI.createURI("https://api.adoptium.net/v3/assets/latest/" + repo + "/hotspot?image_type=jdk&vendor=eclipse");
      String content = getContent(releasesURI);

      Map<Version, List<String>> perVersionDownloadURLs = new TreeMap<>(Comparator.reverseOrder());
      List<String> jdkDownloadURLs = new ArrayList<>();
      for (Matcher assetsMatcher = ASSETS_PATTERN.matcher(content); assetsMatcher.find();)
      {
        String url = assetsMatcher.group(1).replace("%2B", "+");
        Matcher versionMatcher = (beta ? BETA_VERSION_PATTERN : VERSION_PATTERN).matcher(url);
        versionMatcher.find();
        Version version = Version.of(versionMatcher.group(1));
        perVersionDownloadURLs.computeIfAbsent(version, it -> new ArrayList<>()).add(url);

        jdkDownloadURLs.add(url);
      }

      out.println();

      // var entry = perVersionDownloadURLs.entrySet().stream().max((e1, e2) -> Integer.compare(e1.getValue().size(), e2.getValue().size())).get();
      var entry = perVersionDownloadURLs.entrySet().iterator().next();
      Version version = entry.getKey();

      out.println("def java" + repo + "Adoptium = [");
      out.println("  label: 'Java " + repo + " (Adoptium)" + (beta ? " Early Access Beta" : "") + "',");
      out.println("  BUILD_DESCRIPTION: 'Adoptium Java " + version + "',");
      out.println("  PUBLISH_LOCATION_PREFIX: \"${defaultPrefix}\",");
      out.println("  JUSTJ_MANIFEST_URL: \"${justjURL}/${defaultPrefix}/" + repo + "/downloads/latest/justj.manifest\",");

      printEntry(out, "JDK_URLS_WINDOWS", "x64_windows", perVersionDownloadURLs);
      printEntry(out, "JDK_URLS_WINDOWS_AARCH64", "aarch64_windows", perVersionDownloadURLs);

      printEntry(out, "JDK_URLS_MACOS", "x64_mac", perVersionDownloadURLs);
      printEntry(out, "JDK_URLS_MACOS_AARCH64", "aarch64_mac", perVersionDownloadURLs);

      printEntry(out, "JDK_URLS_LINUX", "x64_linux", perVersionDownloadURLs);
      printEntry(out, "JDK_URLS_LINUX_AARCH64", "aarch64_linux", perVersionDownloadURLs);
      printEntry(out, "JDK_URLS_LINUX_PPC64LE", "ppc64le_linux", perVersionDownloadURLs);
      printEntry(out, "JDK_URLS_LINUX_RISCV64", "riscv64_linux", perVersionDownloadURLs);

      out.println("  BUILD_TYPE: 'nightly',");
      out.println("  PROMOTE: 'true'");
      out.println("]");
    }

    out.println();
    out.println(beta ? END_BETA_MARKER : END_MARKER);

    if (arguments.size() > 0)
    {
      Path target = Paths.get(arguments.get(0));
      String contents = Files.readString(target);
      String newGeneratedContents = new String(byteArrayOutputStream.toByteArray(), StandardCharsets.UTF_8);
      if (!contents.contains("\r\n") && newGeneratedContents.contains("\r\n"))
      {
        newGeneratedContents = newGeneratedContents.replace("\r\n", "\n");
      }
      contents = contents.replaceAll(
        "(?s)" + Pattern.quote(beta ? BEGIN_BETA_MARKER : BEGIN_MARKER) + ".*?" + Pattern.quote(beta ? END_BETA_MARKER : END_MARKER) + "\r?\n",
        Matcher.quoteReplacement(newGeneratedContents));
      Files.writeString(target, contents);
    }
  }

  private static void printEntry(PrintStream out, String name, String type, Map<Version, List<String>> perVersionDownloadURLs)
  {
    String jdkURL = getURL(perVersionDownloadURLs, type);
    if (jdkURL != null && !perVersionDownloadURLs.values().iterator().next().contains(jdkURL))
    {
      out.println("  " + name + ": '''");
      out.println("    ''', // " + jdkURL);
    }
    else
    {

      out.println("  " + name + ": '''");
      if (jdkURL != null)
      {
        out.println("    " + jdkURL);
      }
      out.println("    ''',");
    }
  }

  private static String getURL(Map<Version, List<String>> perVersionDownloadURLs, String type)
  {
    for (List<String> downloadURLs : perVersionDownloadURLs.values())
    {
      for (String downloadURL : downloadURLs)
      {
        if (downloadURL.contains(type))
        {
          return downloadURL;
        }
      }
    }

    return null;
  }

  private static Path getCachePath(URI uri)
  {
    if (cache == null)
    {
      return null;
    }

    String decodedURI = URI.decode(uri.toString());
    String[] uriSegments = decodedURI.split("[:/?#&;]+");
    Path result = cache.resolve(String.join("/", uriSegments));
    if (uri.hasTrailingPathSeparator())
    {
      return result.resolve("-folder-contents");
    }
    return result;
  }

  private static String getContent(URI uri) throws IOException
  {
    Path path = getCachePath(uri);
    if (path != null && Files.isRegularFile(path))
    {
      return Files.readString(path);
    }

    try (InputStream in = URIConverter.INSTANCE.createInputStream(uri))
    {
      String content = new String(in.readAllBytes(), StandardCharsets.UTF_8);
      if (path != null)
      {
        Files.createDirectories(path.getParent());
        Files.writeString(path, content);
      }
      return content;
    }
  }

  private static record Version(int major, int minor, int micro, int offset, String suffix) implements Comparable<Version>
  {
    private static final Pattern PARTS = Pattern.compile("(?<major>\\d+)(([.](?<minor>\\d+)([.](?<micro>\\d+))?)?)[+](?<offset>\\d+)(?<suffix>.*)");

    public static Version of(String version)
    {
      Matcher matcher = PARTS.matcher(version);
      if (!matcher.matches())
      {
        throw new IllegalArgumentException(version);
      }

      int major = Integer.parseInt(matcher.group("major"));
      int minor = matcher.group("minor") == null ? 0 : Integer.parseInt(matcher.group("minor"));
      int micro = matcher.group("micro") == null ? 0 : Integer.parseInt(matcher.group("micro"));
      int offset = Integer.parseInt(matcher.group("offset"));
      String suffix = matcher.group("suffix");
      return new Version(major, minor, micro, offset, suffix);
    }

    @Override
    public int compareTo(Version version)
    {
      int compare = Integer.compare(major, version.major);
      if (compare == 0)
      {
        compare = Integer.compare(minor, version.minor);
        if (compare == 0)
        {
          compare = Integer.compare(micro, version.micro);
          if (compare == 0)
          {
            {
              compare = Integer.compare(offset, version.offset);
            }
          }
        }
      }
      return compare;
    }

    @Override
    public final String toString()
    {
      return major + (minor == 0 && micro == 0 ? "" : "." + (minor + (micro == 0 ? "" : "." + micro))) + "+" + offset + suffix;
    }
  }
}
